name: compile MeME

# Controls when the action will run. Workflow runs when manually triggered using the UI
# or API.
on: [push, pull_request, workflow_dispatch]

# This workflow makes x86_64 binaries for mac, windows, and linux.

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        arch: [amd64, arm64]
        targetos: [darwin, linux]
        include:
          - targetos: windows
            arch: amd64
    name: dig ${{ matrix.arch }} for ${{ matrix.targetos }}
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2.1.3
        with: 
          go-version: '^1.17'
        env:
          GOOS: ${{ matrix.targetos }}
          GOARCH: ${{ matrix.arch }}

# we build and install in case we want to run it or capture an artifact as we do in the step below. 
      - name: Compile MeMe
        run: |
          go build ./...
          go install ./...
        
          
          
# now uploads genesis.json and bin
      - uses: actions/upload-artifact@v2
        with:
          name: memed ${{ matrix.targetos }} ${{ matrix.arch }}
          path: cmd/memed
