name: Compile MeMe & zip

# Controls when the action will run.
#  This workflow runr on pushes to master & every Pull Requests. (Or when manually triggered)
on:
  pull_request:
  push:
    tags:
      - '*'
    branches:
      - main
  workflow_dispatch:

# This workflow makes x86_64 binaries for mac, windows, and linux.
jobs:
  version-push-tag:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@master
        with:
          fetch-depth: '0'

      - name: Bump version and push new tag
        id: bump_version
        uses: anothrNick/github-tag-action@1.17.2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          WITH_V: true
          RELEASE_BRANCHES: production

      - name: Save new version number result into file
        shell: bash
        run: |
          echo ${{ steps.bump_version.outputs.tag }} > new_version.txt
      - name: Upload version number for further use
        uses: actions/upload-artifact@v1
        with:
          name: new_version
          path: new_version.txt

      - name: Create version number variable
        id: vars
        run: echo ::set-output name=version_tag_number::${{ steps.bump_version.outputs.tag }}


  build-release:
    needs: version-push-tag
    runs-on: ubuntu-latest
    strategy:
      matrix:
        arch: [amd64]
        targetos: [darwin, linux]
        include:
          - targetos: darwin
            arch: arm64
#        include:
#          - targetos: windows
#            arch: amd64
    name: meme ${{ matrix.arch }} for ${{ matrix.targetos }}
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2.1.4
        with:
          go-version: '^1.18'
        env:
          GOOS: ${{ matrix.targetos }}
          GOARCH: ${{ matrix.arch }}

      - name: Compile MeMe
        run: |
          go mod download
          cd cmd/memed
          go build .
          

      - uses: papeloto/action-zip@v1
        with:
          files: cmd/memed/memed
          dest: memed_${{ matrix.targetos }}_${{ matrix.arch }}.zip

      - uses: actions/upload-artifact@v3.0.0
        with:
          name: memed_${{ matrix.targetos }}_${{ matrix.arch }}
          path: memed_${{ matrix.targetos }}_${{ matrix.arch }}.zip
          
      - name: Download artifacts
        uses: actions/download-artifact@v2

      - name: Display structure of downloaded files
        run: ls -aslR

      - name: Create release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{github.ref_name}}
          release_name: ${{github.ref_name}}

      - name: Upload release assets
        uses: csexton/release-asset-action@v2
        with:
          pattern: "**/*.zip"
          github-token: ${{ secrets.GITHUB_TOKEN }}
          release-url: ${{ steps.create_release.outputs.upload_url }}
