name: Compile MeMe

# Controls when the action will run.
#  This workflow runr on pushes to master & every Pull Requests. (Or when manually triggered)
on:
  pull_request:
  push:
    branches:
      - main
  workflow_dispatch:

# This workflow makes x86_64 binaries for mac, windows, and linux.
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        arch: [amd64]
        targetos: [darwin, linux]
        include:
          - targetos: darwin
            arch: arm64
#        include:
#          - targetos: windows
#            arch: amd64
    name: meme ${{ matrix.arch }} for ${{ matrix.targetos }}
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2.1.4
        with:
          go-version: '^1.18'
        env:
          GOOS: ${{ matrix.targetos }}
          GOARCH: ${{ matrix.arch }}

      - name: Compile MeMe
        run: |
          go mod download
          cd cmd/memed
          go build .
      - uses: actions/upload-artifact@v2
        with:
          upload_url: ${{ steps.get_release.outputs.upload_url }}
          name: memed ${{ matrix.targetos }} ${{ matrix.arch }}
          path: ./memed
          asset_content_type: application/octet-stream
